### PR TITLE
21 feat lightdark mode

### LINKED ISSUE #21: feat: Light/dark mode
# Description

We can try to make light and dark mode, so users can choose between them.

If needed, I will provide all the necessary color hexes

### PR DESCRIPTION
**Pull request by Myjem**
I added light and dark mode. You can change it using an icon in top right corner. Please check how the website looks, if the password eye changes its color while chaning modes and if password stays visible/hidden while changing the mode.

### CODE REVIEW

**Review by xEdziu — CHANGES_REQUESTED** [review]
Add a `cursor: pointer` when hovering over icon to change the style

**Review by xEdziu — CHANGES_REQUESTED** [review]
image

Remember to change scrollbar color when changing theme to light

**Review by Sybirsoldat — DISMISSED** [review]
### GOOD

The theam looks brilliant

### TO CHANGE

Scroll bar doesn't change color

### CONCLUSION

Looks good, only problem i saw was addresed by xEdziu so i will approve

**Review by xEdziu — APPROVED** [review]

**Review by Sybirsoldat — APPROVED** [review]
Ok scroll bar has been fixed, so i'm approving mergeing

**Pull request merged**
